version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: books-postgres
    restart: always
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: wp
      POSTGRES_PASSWORD: wp123
    ports:
      - "5433:5432"
    volumes:
      - pgdata_new:/var/lib/postgresql/data

volumes:
  pgdata_new: